version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  consumer:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        - SERVICE_NAME=consumer
    ports:
      - "8081:8080"
    volumes:
      - ".:/go/src/kafka-demo"
    networks:
      - kafka-net

  producer:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        - SERVICE_NAME=producer
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/kafka-demo"
    networks:
      - kafka-net

networks:
  kafka-net:
